/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_test_ModifyDoubleArray */

#ifndef _Included_com_test_ModifyDoubleArray
#define _Included_com_test_ModifyDoubleArray
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_test_ModifyDoubleArray
 * Method:    modifyArray
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_com_test_ModifyDoubleArray_modifyArray
  (JNIEnv *, jobject, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif

